hooks:
  # applypatch-msg:
  #   scripts:
  #     - echo Running "applypatch-msg" hook

  # commit-msg:
  #   scripts:
  #     - echo Running "commit-msg" hook

  # post-update:
  #   scripts:
  #     - echo Running "post-update" hook

  # pre-applypatch:
  #   scripts:
  #     - echo Running "pre-applypatch" hook

  pre-commit:
    scripts:
      - echo Running "pre-commit" hook ... Please add more scripts!!!
      # - flake8 --max-line-length=120 --exclude .git,build,dist,.env,.venv

  # prepare-commit-msg:
  #   scripts:
  #     - echo Running 'prepare-commit-msg' hook

  pre-push:
    scripts:
      - echo Running 'pre-push' hook ... Please add more scripts!!!
      # - nosetests --with-coverage

  # pre-rebase:
  #   scripts:
  #     - echo 'Running "pre-rebase" hook\n'

  # update:
  #   scripts:
  #     - echo 'Running "update" hook\n'
