language: python
cache:
- pip
- npm
addons:
  apt:
    update: true
    packages:
    - nodejs
    - npm
  homebrew:
    update: true
    packages:
    - node
    - python3
    # - gnu-sed
matrix:
  include:
    # - name: "Python 3.5.6 on Linux"
    #   python: 3.5           # this works for Linux but is ignored on macOS or Windows
    #   before_install:
    #     - sed -i 's/black = "\*"//g' Pipfile
    #     - pip3 install -U pip pipenv
    #     - pip3 install .
    # - name: "Python 3.6.3 on Linux"
    #   python: 3.6           # this works for Linux but is ignored on macOS or Windows
    #   before_install:
    #     - pip3 install -U pip pipenv
    #     - pip3 install .
    # - name: "Python 3.7.1 on Linux"
    #   python: 3.7           # this works for Linux but is ignored on macOS or Windows
    #   dist: xenial          # required for Python >= 3.7
    #   before_install:
    #     - pip3 install -U pip pipenv
    #     - pip3 install .
    # - name: "Python 3.7.3 on macOS"
    #   os: osx
    #   osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
    #   before_install:
    #     - pip3 install -U pip pipenv
    #     - pip3 install .
    #   language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      env: "PATH=/c:/c/Python37:/c/Python37/Scripts:/c/Users/travis/AppData/Roaming/Python/Python37/Scripts:/c/Progra~1/nodejs:$PATH"
      before_install:
        - choco install python nodejs
        - cp $(which python) /c/python3
        - pip3 install -U pip pipenv --user
        - pip3 install . --user
# before_install: pip3 install -U pip pipenv
install:
- npm install
script:
- python --version || true
- python2 --version || true
- python3 --version || true
- which hooks4git
- hooks4git -h
- pwd
- hooks4git -t ci
after_success:
- coveralls
deploy:
- provider: pypi
  user: marco.lovato
  password:
    secure: E1ayTfE3K+HL8qk6aMmh4qNItmn1DtDDBBAXrtUica/o9dtToSFePFqjDR3nJQAe58pjky/TWzCX494iAZwOfFKVBABj0LUc97fefQyHhnBkIoPYt0saZPEKV6vi08qqaYlSFESwxQ70n/wXOvsJjWmafP0sLledB3AtQ6x790CspioFAW+USl/CZC8SLtK5zJHjLWZeoKPC4S15YX6l57T5LaC+qGeUPAaEhzG/sjJKvunw/ZdM9d8l6YchXfvPDPH2siaYJN3jU49tTjVWy6NoIax2LjutRf9WRvmsfQFgknIprWel8GZ8GvCI3yv8mGIYyuch+6sT3EcRg7+wX6bbd4p8bFAgAk0dDKOdDFi6j8L95+SHRKa2d0OLhm0apQX+lRmq3QizH2mFz3mMpvRYsw9oNh/nYTkAOUlpk75k2Uwoqh5Aqc1ljivBJIbkt4zbsKpUiLEmq+hEoVNZlhjGnfrJiHM34UIMCJuPl+vbp3LoW6xtoICaWSW0MGcsiy7+dOzYRzhVo6Y2a5HKoM5/buz1RZlR3UsJ3K7fmYL0JbyCXJbCP0Nhm7H70G5sS01rmSFmuN2/jkcf91DzyHFZ6SyKxCYxBmMyHy4MMG72DeuNLYBf7fRXiUdEZD/oM+PAIH/PwSUBLhpWMntIbAaDgbCuc3w1uvNaeECf3BE=
  on:
    branch: master
    python: '3.6'
- provider: pypi
  server: https://test.pypi.org/legacy/
  user: marco.lovato
  password:
    secure: E1ayTfE3K+HL8qk6aMmh4qNItmn1DtDDBBAXrtUica/o9dtToSFePFqjDR3nJQAe58pjky/TWzCX494iAZwOfFKVBABj0LUc97fefQyHhnBkIoPYt0saZPEKV6vi08qqaYlSFESwxQ70n/wXOvsJjWmafP0sLledB3AtQ6x790CspioFAW+USl/CZC8SLtK5zJHjLWZeoKPC4S15YX6l57T5LaC+qGeUPAaEhzG/sjJKvunw/ZdM9d8l6YchXfvPDPH2siaYJN3jU49tTjVWy6NoIax2LjutRf9WRvmsfQFgknIprWel8GZ8GvCI3yv8mGIYyuch+6sT3EcRg7+wX6bbd4p8bFAgAk0dDKOdDFi6j8L95+SHRKa2d0OLhm0apQX+lRmq3QizH2mFz3mMpvRYsw9oNh/nYTkAOUlpk75k2Uwoqh5Aqc1ljivBJIbkt4zbsKpUiLEmq+hEoVNZlhjGnfrJiHM34UIMCJuPl+vbp3LoW6xtoICaWSW0MGcsiy7+dOzYRzhVo6Y2a5HKoM5/buz1RZlR3UsJ3K7fmYL0JbyCXJbCP0Nhm7H70G5sS01rmSFmuN2/jkcf91DzyHFZ6SyKxCYxBmMyHy4MMG72DeuNLYBf7fRXiUdEZD/oM+PAIH/PwSUBLhpWMntIbAaDgbCuc3w1uvNaeECf3BE=
  on:
    branch: develop
    python: '3.6'
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: LwmtPkwyfoITVgDsbejKchM2vwsPq70zVYpfyqVbFUCys8qFII16HEmz38PDV8SujggbUsmJd1Oug0vW6K0Ie/VSXrZoDleJBTVxsgACNjiFXYca3ZDxpKw0tkfCF9MMM2Wjns5JfW28sqktHddpsC+VWgEG2Fv169/ouOAxiiCiUiTxM9Pmsg9RT89CaHjlrjlHvKg9OgGai3rEvp5rAyvJNvr4yfMyXBozvamNA8u1i7DniB9Jueq06OdBM6JjhiNC0lLoDHvcuvjhhm5P3eh4lzuUxbktyyujcBb6UGXH0Pd0mnyWRlHILseCL/a26dxNtgE3SNcbZHR/aSNhXu7vlVPx9Tf+s/XpHhWTJeofka/+iAGDXkOwlw+ycmrZZt5gDtq0vYS3f+lYDFcCxst6ToJfB9lXV7hnpg2WDvjo7aHx4dvxI/18CGwfOK4JNQxpJfsAMIGjwPPes4FmewSIsDSBygrn39CAhKryOifdR9bqqihjEFqGfSUe3JjOV95Wb13SwTEO17qoZQSpqjt6VwH7VCeAKaHfcWBDEQzRJxLi/Az25iOxbloJdc0wl22t7o6zMr3EaAGjI8HaE9KTIiBiBwU/4HjxjnuKFSH6c6LdHa5BHtfhgqSpNnXnHmdCschBPD5qEwrjPdQ73g/dkzel1RmNIwwUzCmpksw=
