language: python

python:
    - '3.5'

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - flake8 --max-line-length=120 --exclude .git,__pycache__,build,dist
    - nosetests --with-coverage

deploy:
  - provider: pypi
    user: marco.lovato
    password:
        secure: xrJxZMnzeXHszYt1g7xLiPzxkHbsP2Tjj6fjvDK3iPMN0wlnGfhDmYEV5cVPMzkpTi1T9mtatoB2BjTDZL7fuEdSv59mvP39soj8qqj/i6opOCQqepvDPRMaCCq7hT/ViUcgSho9h5NBTiHvblhtrOic+hZTVVjt2nG4uCP2af0=
    on:
        branch: master
  - provider: pypi
    server: https://test.pypi.org/pypi
    user: marco.lovato
    password:
        secure: xrJxZMnzeXHszYt1g7xLiPzxkHbsP2Tjj6fjvDK3iPMN0wlnGfhDmYEV5cVPMzkpTi1T9mtatoB2BjTDZL7fuEdSv59mvP39soj8qqj/i6opOCQqepvDPRMaCCq7hT/ViUcgSho9h5NBTiHvblhtrOic+hZTVVjt2nG4uCP2af0=
    on:
        branch: develop

notifications:
    email: true

after_success:
  - coveralls